tokens = (
    'INTEGER', 'FLOAT', 'STRING', 'BOOLEAN',
    'IDENTIFIER',
    'FUNCTION', 'IF', 'ELSE', 'FOR', 'WHILE', 'RETURN', 'VAR', 'CONST', 'TRUE', 'FALSE',
    'ASSIGN','PRINT',
    'PLUS', 'MINUS', 'TIMES', 'DIVIDE', 'MODULUS',
    'EQUAL', 'NOT_EQUAL', 'GREATER_THAN', 'LESS_THAN', 'GREATER_THAN_OR_EQUAL', 'LESS_THAN_OR_EQUAL',
    'AND', 'OR', 'NOT',
    'LPREN', 'RPREN',
    'LEFT_CURLY_BRACE', 'RIGHT_CURLY_BRACE',
    'LEFT_SQUARE_BRACKET', 'RIGHT_SQUARE_BRACKET',
    'COMMA', 'SEMICOLON', 'COLON', 'DOT',
    'RIGHT_ARROW', 'LEFT_ARROW',
)
